version: '3.9'

services:
  webapp:
    build:
      context: ./webapp
    container_name: php_app
    volumes:
      - ./webapp:/var/www/html
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./webapp:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - webapp

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
