version: '3.8'

services:
  web:
    image: php:7.4-fpm
    container_name: webapp
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app-network
  
  mariadb:
    image: mariadb:10.5
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: reservation
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

  reverse-proxy:
    image: jwilder/nginx-proxy
    container_name: reverse-proxy
    environment:
      - DEFAULT_HOST=reservation-salles  # Définit le nom de domaine par défaut
    ports:
      - "80:80"  # Mappe le port 80 sur la machine hôte vers le container reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf   # Utilise la configuration personnalisée
      - /var/run/docker.sock:/tmp/docker.sock:ro  # Permet à Nginx de détecter les containers Docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge