# Utiliser une image PHP avec Nginx pré-installé
FROM php:8.2-fpm

# Installer les extensions nécessaires pour MariaDB
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copier les fichiers de l'application
COPY . /var/www/html/

# Définir le dossier de travail
WORKDIR /var/www/html/